#!/bin/bash
# Script to perform post provisioning of an ubuntu server in Softlayer
# Sets up machine to kill itself after 1 hour

{
# Create iptables rules
iptables-restore <<EOT
# Generated by iptables-save v1.4.21 on Tue Jul  1 10:13:19 2014
*nat
:PREROUTING ACCEPT [21:1248]
:INPUT ACCEPT [2:100]
:OUTPUT ACCEPT [178:10832]
:POSTROUTING ACCEPT [178:10832]
-A POSTROUTING -o eth1 -j MASQUERADE
COMMIT
# Completed on Tue Jul  1 10:13:19 2014
# Generated by iptables-save v1.4.21 on Tue Jul  1 10:13:19 2014
*filter
:INPUT DROP [7:420]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [110:13956]
-A INPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -i eth0 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
COMMIT
# Completed on Tue Jul  1 10:13:19 2014
EOT
iptables -L -vn

echo "Updating server..."
apt-get update && apt-get dist-upgrade -y

echo "Installing softlayer python..."
apt-get install python-pip -y
pip install softlayer

echo "Adding API credentials..."
cat >/root/.softlayer <<EOT
[softlayer]
username = <soflayer id>
api_key = <api key>
endpoint_url = https://api.softlayer.com/xmlrpc/v3.1/
EOT

echo "Preparing self destruction..."
KILL="/root/killme"
apt-get install at -y
cat >$KILL <<EOT
/usr/local/bin/sl vs cancel `/usr/local/bin/sl my id` -y
EOT

at now+1hour -f $KILL

echo "Done"
} > $0.log
